services:
  backend:
    container_name: fastapi_app
    build: ./
    ports:
      - 8000:8000
    env_file: ./example.env
    command: bash -c "alembic upgrade head && python3 main.py"
    volumes:
      - ./src:/src